### PR TITLE
show more information from API

### PR DESCRIPTION
**Pull request by dangenendt**
@RickBakkr 
Here is my PR. 
With smaller refactorings. Would have done more refactoring but this is another issue what @redbrickone wnats to do. @redbrickone can you have a small look too, so that there will be not so much conflicts. Thanks
 
New Message is like this:

** HETZNER DEAL FOUND **
4x RAM 8192 MB DDR3 ECC 2x HDD SATA 2,0 TB Enterprise NIC 1 Gbit - Intel I210 2x 2 TB Intel Xeon E3-1271V3 SB32 922077 ECC Ent. HDD iNIC
CPU: Intel Xeon E3-1271V3 (Benchmark: 10140)

Details: 
4x RAM 8192 MB DDR3 ECC
2x HDD SATA 2,0 TB Enterprise
NIC 1 Gbit - Intel I210

Specials: ECC / Ent. HDD / iNIC

Dedicated is located in: FSN1-DC12 :de:

Cost is: €26.8908 (approx. €32.537868 incl. 21% VAT) 

https://robot.your-server.de/order/marketConfirm/922077

### CODE REVIEW

**Comment by RickBakkr** [comment]
Awesome! Good job, thanks for the great work. 
Will merge it, given I have not seen a fork by @redbrickone, I assume he has not started working, in which case it should not interfere.

**Comment by dangenendt** [comment]
@RickBakkr 
Ok, if he do not wants to do it, i would give it a try. 

I guess issue https://github.com/RickBakkr/hetzner-notify/issues/5 can be closed right? Except you want to have some info in the message :relaxed:

**Comment by RickBakkr** [comment]
Not really, I believe the creator of #5 is aiming at filtering based on those "features", which I believe is not built-in yet? Correct me if I am wrong though...

**Comment by dangenendt** [comment]
Ahhhh :rofl: 
Now i get it. 
Will do that tomorrow. Seems like i need to sleep :man_facepalming:

**Comment by dangenendt** [comment]
Yeah... so much truth in this pic. 
Im on it. Now. :D

**Pull request merged**
